"""
Energy Fuels Inc. (UUUU) — Q4 & FY2025 Earnings Update
Institutional equity research report builder — English version (DOCX)
Run: python build_uuuu_report.py
Requires: python-docx, matplotlib (charts already generated by build_uuuu_charts.py)
"""
import os
from docx import Document
from docx.shared import Pt, Inches, RGBColor, Cm
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_ALIGN_VERTICAL, WD_TABLE_ALIGNMENT
from docx.oxml.ns import qn
from docx.oxml import OxmlElement

BASE = "/Users/macrossz/DevTools/VscodeProject/ClaudeCode/financial_analysis/output/UUUU"

C_NAVY   = RGBColor(0x1C, 0x1C, 0x4D)
C_BLUE   = RGBColor(0x00, 0x71, 0xE3)
C_GREEN  = RGBColor(0x1E, 0x8A, 0x44)
C_RED    = RGBColor(0xCC, 0x00, 0x00)
C_GREY   = RGBColor(0x8E, 0x8E, 0x93)
C_LTBLUE = RGBColor(0xE8, 0xF2, 0xFF)
C_AMBER  = RGBColor(0xE6, 0x7E, 0x22)
C_WHITE  = RGBColor(0xFF, 0xFF, 0xFF)

# ── Helpers ────────────────────────────────────────────────────────────────────
def set_cell_bg(cell, hex_color):
    tc_pr = cell._tc.get_or_add_tcPr()
    shd = OxmlElement("w:shd")
    shd.set(qn("w:val"), "clear")
    shd.set(qn("w:color"), "auto")
    shd.set(qn("w:fill"), hex_color)
    tc_pr.append(shd)

def set_cell_border(cell, sides=("top","bottom","left","right"), size="4", color="CCCCCC"):
    tc_pr = cell._tc.get_or_add_tcPr()
    tc_borders = OxmlElement("w:tcBorders")
    for side in sides:
        border = OxmlElement(f"w:{side}")
        border.set(qn("w:val"), "single")
        border.set(qn("w:sz"), size)
        border.set(qn("w:space"), "0")
        border.set(qn("w:color"), color)
        tc_borders.append(border)
    tc_pr.append(tc_borders)

def heading(doc, text, level=1, color=None):
    p = doc.add_paragraph()
    p.clear()
    run = p.add_run(text)
    if level == 1:
        run.font.size = Pt(18)
        run.font.bold = True
        run.font.color.rgb = C_NAVY
    elif level == 2:
        run.font.size = Pt(13)
        run.font.bold = True
        run.font.color.rgb = color or C_NAVY
        p.paragraph_format.space_before = Pt(12)
        p.paragraph_format.space_after  = Pt(4)
        pPr = p._p.get_or_add_pPr()
        pBdr = OxmlElement("w:pBdr")
        bottom = OxmlElement("w:bottom")
        bottom.set(qn("w:val"), "single")
        bottom.set(qn("w:sz"), "6")
        bottom.set(qn("w:space"), "1")
        bottom.set(qn("w:color"), "1C1C4D")
        pBdr.append(bottom)
        pPr.append(pBdr)
    elif level == 3:
        run.font.size = Pt(11)
        run.font.bold = True
        run.font.color.rgb = color or C_BLUE
        p.paragraph_format.space_before = Pt(8)
        p.paragraph_format.space_after  = Pt(2)
    return p

def body(doc, text, bold=False, italic=False, color=None, size=10, space_after=4):
    p = doc.add_paragraph()
    run = p.add_run(text)
    run.font.size = Pt(size)
    run.font.name = "Times New Roman"
    run.font.bold = bold
    run.font.italic = italic
    if color:
        run.font.color.rgb = color
    p.paragraph_format.space_after = Pt(space_after)
    return p

def bullet(doc, text, level=0, color=None):
    p = doc.add_paragraph(style="List Bullet")
    run = p.add_run(text)
    run.font.size = Pt(10)
    run.font.name = "Times New Roman"
    if color:
        run.font.color.rgb = color
    p.paragraph_format.left_indent = Inches(0.25 + 0.2 * level)
    p.paragraph_format.space_after = Pt(2)
    return p

def add_image(doc, filename, width=Inches(6.5), caption=None):
    path = os.path.join(BASE, filename)
    if not os.path.exists(path):
        body(doc, f"[Chart: {filename} not found — run build_uuuu_charts.py first]", italic=True, color=C_GREY)
        return
    doc.add_picture(path, width=width)
    last_para = doc.paragraphs[-1]
    last_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    if caption:
        cp = doc.add_paragraph(caption)
        cp.alignment = WD_ALIGN_PARAGRAPH.CENTER
        for run in cp.runs:
            run.font.size = Pt(8.5)
            run.font.italic = True
            run.font.color.rgb = C_GREY
        cp.paragraph_format.space_after = Pt(6)

def add_table(doc, headers, rows, col_widths=None, alternate=True):
    table = doc.add_table(rows=1 + len(rows), cols=len(headers))
    table.style = "Table Grid"
    table.alignment = WD_TABLE_ALIGNMENT.CENTER
    hrow = table.rows[0]
    for i, hdr in enumerate(headers):
        cell = hrow.cells[i]
        cell.text = hdr
        set_cell_bg(cell, "1C1C4D")
        set_cell_border(cell)
        for run in cell.paragraphs[0].runs:
            run.font.bold = True
            run.font.color.rgb = C_WHITE
            run.font.size = Pt(9)
        cell.paragraphs[0].alignment = WD_ALIGN_PARAGRAPH.CENTER
    for ri, row_data in enumerate(rows):
        row = table.rows[ri + 1]
        bg = "F0F4FF" if (alternate and ri % 2 == 0) else "FFFFFF"
        for ci, val in enumerate(row_data):
            cell = row.cells[ci]
            cell.text = str(val)
            set_cell_bg(cell, bg)
            set_cell_border(cell)
            for run in cell.paragraphs[0].runs:
                run.font.size = Pt(9)
                run.font.name = "Calibri"
            cell.paragraphs[0].alignment = WD_ALIGN_PARAGRAPH.CENTER
    if col_widths:
        for i, w in enumerate(col_widths):
            for row in table.rows:
                row.cells[i].width = Inches(w)
    return table

def page_break(doc):
    doc.add_page_break()

def divider(doc):
    p = doc.add_paragraph()
    pPr = p._p.get_or_add_pPr()
    pBdr = OxmlElement("w:pBdr")
    bottom = OxmlElement("w:bottom")
    bottom.set(qn("w:val"), "single")
    bottom.set(qn("w:sz"), "4")
    bottom.set(qn("w:space"), "1")
    bottom.set(qn("w:color"), "CCCCCC")
    pBdr.append(bottom)
    pPr.append(pBdr)
    p.paragraph_format.space_after = Pt(4)


# ══════════════════════════════════════════════════════════════════════════════
def build_report():
    doc = Document()

    # Page margins
    for section in doc.sections:
        section.top_margin    = Cm(1.8)
        section.bottom_margin = Cm(1.8)
        section.left_margin   = Cm(2.0)
        section.right_margin  = Cm(2.0)

    # ── COVER / HEADER ─────────────────────────────────────────────────────────
    p = doc.add_paragraph()
    run = p.add_run("EQUITY RESEARCH  |  URANIUM & CRITICAL MINERALS")
    run.font.size = Pt(9)
    run.font.color.rgb = C_GREY
    run.font.bold = True
    p.paragraph_format.space_after = Pt(2)

    heading(doc, "Energy Fuels Inc. (UUUU / EFR.TSX)", level=1)

    p = doc.add_paragraph()
    run = p.add_run("Q4 & Full Year 2025 Earnings Update  |  Rating: BUY (Consensus)  |  Price Target: $27.25 (H.C. Wainwright)")
    run.font.size = Pt(11)
    run.font.bold = True
    run.font.color.rgb = C_BLUE
    p.paragraph_format.space_after = Pt(4)

    p = doc.add_paragraph()
    run = p.add_run("Date: March 17, 2026  |  Reporting Date: February 26–27, 2026  |  Current Price: ~$18.67  |  Market Cap: ~$4.51B")
    run.font.size = Pt(9.5)
    run.font.color.rgb = C_GREY
    p.paragraph_format.space_after = Pt(8)

    divider(doc)

    # ── INVESTMENT SUMMARY BOX ─────────────────────────────────────────────────
    heading(doc, "Investment Summary", level=2)
    body(doc,
         "Energy Fuels (UUUU) reported Q4 and full year 2025 results on February 26–27, 2026. "
         "The company delivered a breakout year operationally — mining 1.72M lbs U3O8 (exceeding guidance by ~11%), "
         "processing 1.015M lbs of finished uranium, and closing a landmark $700M convertible note offering that lifted "
         "working capital to ~$927M. Revenue came in at $27.1M for Q4 and $65.9M for FY2025, down from $78.1M in 2024 "
         "due to the winding down of Kwale HMS operations. The net loss widened to $86.1M ($0.38/share) as the company "
         "absorbs costs of an aggressive multi-front growth strategy spanning uranium, rare earth elements (REE), "
         "heavy mineral sands (HMS), and medical isotopes."
    )
    body(doc,
         "Key positives: uranium COGS/lb fell from $53 to $43; six long-term contracts secured through 2032; "
         "dysprosium oxide pilot production validated by South Korean automotive manufacturers; Phase 2 REE feasibility "
         "study shows $1.9B NPV ($410M capex); and management succession secured (Ross Bhappu becomes CEO April 15, 2026). "
         "On the negative side, Q4 EPS of ($0.08) missed consensus of ($0.07) by $0.01.",
         space_after=8
    )

    # Key metrics snapshot
    heading(doc, "Key Metrics Snapshot", level=3)
    add_table(doc,
        headers=["Metric", "Q4 2025", "Q4 2024", "FY2025", "FY2024"],
        rows=[
            ["Total Revenue ($M)", "$27.1", "$39.9", "$65.9", "$78.1"],
            ["Uranium Revenue ($M)", "~$27.1", "~$12.6", "$48.2", "$37.9"],
            ["Heavy Mineral Sands ($M)", "—", "~$27.3", "$15.8", "$39.9"],
            ["Net Income/(Loss) ($M)", "($20.9)", "($28.8)", "($86.1)", "($47.8)"],
            ["EPS (Basic)", "($0.08)", "($0.19)", "($0.38)", "($0.28)"],
            ["EPS vs Consensus", "Miss ($0.01)", "Miss ($0.12)", "—", "Miss ($0.18)"],
            ["Revenue vs Consensus", "+$0.1M Beat", "—", "—", "—"],
            ["Uranium Sold (klbs)", "360", "~150", "650", "450"],
            ["Avg Realized Price ($/lb)", "$74.93", "~$84.0", "$74.21", "$87.2"],
            ["Working Capital ($M)", "—", "—", "$927.4", "$170.9"],
        ],
        col_widths=[2.3, 1.1, 1.1, 1.1, 1.1]
    )
    body(doc, "Sources: Energy Fuels press releases (Feb 26, 2026; Dec 29, 2025); Zacks; H.C. Wainwright research.", italic=True, color=C_GREY, size=8.5, space_after=10)

    add_image(doc, "uuuu_chart1_revenue.png", caption="Chart 1: UUUU Quarterly Revenue by Segment (Q1 2024 – Q4 2025)")

    # ── SECTION 1: Q4 2025 DETAILED RESULTS ────────────────────────────────────
    page_break(doc)
    heading(doc, "1. Q4 2025 Detailed Financial Results", level=2)

    heading(doc, "Revenue & Earnings", level=3)
    body(doc,
         "Q4 2025 total revenue was $27.1M, a beat of $0.1M (+0.38%) vs the Zacks consensus estimate of $27.0M. "
         "This compares to $39.9M in Q4 2024, with the decline entirely attributable to the cessation of Kwale "
         "Heavy Mineral Sands (HMS) mine operations (which concluded reclamation activities at year-end 2024). "
         "Uranium concentrates drove essentially all Q4 2025 revenue."
    )
    bullet(doc, "Uranium revenue Q4 2025: ~$27.0M (360,000 lbs × $74.93/lb weighted average realized price)")
    bullet(doc, "Heavy mineral sands revenue Q4 2025: Minimal / nil (Kwale HMS ceased production)")
    bullet(doc, "Vanadium revenue: $0 (905,000 lbs V2O5 held in inventory, not sold — awaiting improved market conditions)")
    bullet(doc, "REE/NdPr oxide revenue: minimal at pilot-scale; no commercial REE sales revenue booked in Q4 2025")
    body(doc, "", space_after=4)

    heading(doc, "EPS & Net Income", level=3)
    body(doc,
         "Q4 2025 net loss was approximately ($20.9M), or ($0.08) per diluted share, versus the consensus estimate "
         "of ($0.07) — a miss of $0.01/share. This compares favorably to Q4 2024's loss of ($28.8M) or ($0.19)/share, "
         "reflecting improved uranium unit economics despite higher corporate costs associated with the convertible note "
         "offering and ramp-up investments."
    )
    bullet(doc, "Q4 2025 EPS: ($0.08) actual vs ($0.07) consensus  →  MISS by $0.01")
    bullet(doc, "Q4 2024 EPS: ($0.19)  |  Q3 2025 EPS: ($0.07)  |  Q2 2025 EPS: ($0.10)")
    body(doc, "", space_after=4)

    heading(doc, "Uranium Operations — Q4 2025", level=3)
    body(doc,
         "The uranium segment was the primary driver of Q4 2025 performance, with the White Mesa Mill operating "
         "its conventional ore processing campaign (commenced Q4 2025, expected to continue through Q2 2026). "
         "The mill demonstrated an ability to average ~250,000 lbs/month, including 350,000 lbs of finished U3O8 "
         "produced in December 2025 alone."
    )
    add_table(doc,
        headers=["Metric", "Q4 2025", "Q3 2025", "Q2 2025", "Q1 2025"],
        rows=[
            ["Uranium Sold (klbs)", "360", "240", "~150", "~50"],
            ["Avg Realized Price ($/lb)", "$74.93", "$69.6 (est.)", "$79.0 (est.)", "$80.0 (est.)"],
            ["Uranium Revenue ($M)", "~$27.0", "~$10.4", "~$4.2", "~$7.0"],
            ["Spot Sales (klbs)", "N/A Q4", "—", "—", "—"],
            ["Contract Sales (klbs)", "N/A Q4", "—", "—", "—"],
            ["COGS/lb (approx.)", "~$43", "~$43", "~$47", "~$50"],
        ],
        col_widths=[2.2, 1.2, 1.2, 1.2, 1.2]
    )
    body(doc, "Note: Q2 and Q1 2025 uranium revenue estimated from total quarterly revenues net of HMS contribution.", italic=True, color=C_GREY, size=8.5)
    body(doc, "", space_after=6)

    add_image(doc, "uuuu_chart2_uranium_ops.png", caption="Chart 2: Uranium Sales Volume & Realized Price per Pound (Q1 2024 – Q4 2025)")

    heading(doc, "Vanadium", level=3)
    body(doc,
         "Energy Fuels held 905,000 lbs of finished V2O5 in inventory as of Q3 2025 (no update to year-end 2025 "
         "inventory provided in the press release, implying no material sales). The company has elected to hold "
         "vanadium inventory and not sell below management's target price. No vanadium revenue was recognized in "
         "FY2025 (also $0 in FY2024). The vanadium inventory represents a meaningful optionality call on vanadium "
         "prices, which are currently around $6–7/lb."
    )

    heading(doc, "Rare Earth Elements — Q4 2025 Milestones", level=3)
    body(doc,
         "No commercial REE revenue was booked in Q4 or FY2025 from separated rare earth oxides (beyond minimal "
         "pilot-scale production). However, the company achieved critical qualitative milestones:"
    )
    bullet(doc, "29 kg of dysprosium (Dy) oxide produced at 99.9% purity at White Mesa Mill by Q3 2025")
    bullet(doc, "Dy oxide validated by a major South Korean automotive manufacturer (permanent magnet use in EV motors)")
    bullet(doc, "1.2 MT of NdPr oxide manufactured into ~3.0 MT of rare earth permanent magnets powering ~1,500 EV vehicles")
    bullet(doc, "First kilogram of terbium (Tb) oxide production targeted for early Q1 2026")
    bullet(doc, "Inventory as of Q3 2025: 37,000 kg finished NdPr oxide; 9,000 kg Sm+ heavy REE carbonate")
    body(doc, "", space_after=4)

    add_image(doc, "uuuu_chart3_net_income.png", caption="Chart 3: Quarterly Net Income/(Loss) & EPS (Q1 2024 – Q4 2025)")
    add_image(doc, "uuuu_chart4_beat_miss.png", caption="Chart 4: 2025 Quarterly Earnings vs Consensus Estimates")

    # ── SECTION 2: FULL YEAR 2025 ──────────────────────────────────────────────
    page_break(doc)
    heading(doc, "2. Full Year 2025 Financial Results", level=2)

    heading(doc, "Income Statement Summary", level=3)
    add_table(doc,
        headers=["", "FY2025", "FY2024", "Change", "Notes"],
        rows=[
            ["Total Revenue ($M)", "$65.9", "$78.1", "–15.6%", "Kwale HMS wind-down"],
            ["  Uranium Concentrates", "$48.2", "$37.9", "+27.2%", "650k lbs @ $74.21/lb"],
            ["  Heavy Mineral Sands", "$15.8", "$39.9", "–60.4%", "Kwale final yr / Donald pending"],
            ["  Vanadium", "$0", "$0", "—", "905k lbs held in inventory"],
            ["  REE / Other", "~$1.9", "~$0.3", "—", "Pilot-scale / minimal"],
            ["Gross Profit ($M)", "~$20.3", "~$28.2", "–28.0%", "Uranium: ~42% GM"],
            ["Operating Loss ($M)", "(~$58M)", "(~$19M)", "—", "SG&A + exploration + DD&A"],
            ["Net Loss ($M)", "($86.1)", "($47.8)", "–80.1%", "Incl. conv. note offering costs"],
            ["Net Loss per Share", "($0.38)", "($0.28)", "–35.7%", "Shares ~226M diluted"],
        ],
        col_widths=[2.3, 1.0, 1.0, 1.0, 2.2]
    )
    body(doc, "Source: Energy Fuels press release, February 26, 2026 (PRNewswire).", italic=True, color=C_GREY, size=8.5)
    body(doc, "", space_after=6)

    heading(doc, "Uranium Segment — Full Year 2025", level=3)
    add_table(doc,
        headers=["Metric", "FY2025", "FY2024"],
        rows=[
            ["Uranium Sold (klbs)", "650", "450"],
            ["Avg Realized Price ($/lb)", "$74.21", "$87.2"],
            ["  — Spot Sales", "350k lbs @ $76.90/lb", "250k lbs @ $91.51/lb"],
            ["  — Contract Sales", "300k lbs @ $71.06/lb", "200k lbs @ $75.13/lb"],
            ["Uranium Revenue ($M)", "$48.2", "$37.9"],
            ["COGS/lb (weighted avg)", "~$43", "~$53"],
            ["Gross Margin (uranium)", "~42%", "~56%"],
            ["Mined ore (Mlbs U3O8)", "1.72", "1.10"],
            ["Processed/finished (Mlbs)", "1.015", "0.55"],
            ["Long-term contracts", "6 (through 2032)", "4"],
        ],
        col_widths=[3.0, 2.0, 2.0]
    )
    body(doc, "", space_after=4)

    body(doc,
         "The FY2025 uranium segment demonstrates a clear positive trajectory: volumes sold increased 44% YoY, "
         "production nearly doubled, and unit costs fell meaningfully. While the realized price declined from "
         "$87.2/lb to $74.21/lb (reflecting the slide in uranium spot prices from 2024 peaks toward $63–$83/lb "
         "range in 2025), the economics remain robust at a ~42% gross margin.",
         space_after=8
    )

    heading(doc, "Uranium Inventory Position (as of December 31, 2025)", level=3)
    add_table(doc,
        headers=["Category", "Lbs U3O8", "Notes"],
        rows=[
            ["Mined ore / mineralized material", "1,240,000", "Underground and surface stockpile"],
            ["Work-in-process", "130,000", "At White Mesa Mill"],
            ["Finished U3O8", "810,000", "Ready for delivery / sale"],
            ["TOTAL", "~2,180,000", "~2x End-2024 inventory of ~980k lbs"],
        ],
        col_widths=[2.8, 1.6, 3.0]
    )
    body(doc, "", space_after=8)

    add_image(doc, "uuuu_chart5_annual_revenue.png", caption="Chart 5: Annual Revenue by Segment (FY2023–FY2025)")
    add_image(doc, "uuuu_chart6_uranium_production.png", caption="Chart 6: Uranium Mining, Processing & Inventory (lbs U3O8)")

    heading(doc, "Balance Sheet (December 31, 2025)", level=3)
    add_table(doc,
        headers=["Item", "Dec 31, 2025", "Dec 31, 2024"],
        rows=[
            ["Working Capital", "$927.4M", "$170.9M"],
            ["Cash & Cash Equivalents", "$64.7M", "$38.6M"],
            ["Marketable Securities", "$797.1M", "$80.9M"],
            ["Total Cash & Securities", "~$861.8M", "~$119.5M"],
            ["Trade Receivables", "~$22M (est.)", "$37.8M"],
            ["Inventory (all)", "~$100M+ (est.)", "$66.5M"],
            ["Total Assets", "$1,410M", "~$470M"],
            ["Total Liabilities", "$729.3M", "~$0 (no debt)"],
            ["Convertible Senior Notes", "$700M @ 0.75%", "—"],
            ["Net Equity", "~$680M", "~$470M"],
        ],
        col_widths=[2.8, 1.8, 1.8]
    )
    body(doc,
         "The $700M convertible note offering (October 2025, 0.75% coupon, 7x+ oversubscribed, mature 2031) "
         "transformed the balance sheet. Initial conversion price: $20.34/share. With capped call overlays, "
         "the effective dilution threshold rises to $30.70/share (100% premium to issue price).",
         space_after=6
    )

    add_image(doc, "uuuu_chart7_cost_structure.png", caption="Chart 7: Uranium Cost Structure vs Realized Price")
    add_image(doc, "uuuu_chart8_balance_sheet.png", caption="Chart 8: Balance Sheet Highlights")

    # ── SECTION 3: URANIUM MARKET CONTEXT ──────────────────────────────────────
    page_break(doc)
    heading(doc, "3. Uranium & REE Market Context", level=2)

    heading(doc, "Uranium Spot Price — 2025 Trend", level=3)
    body(doc,
         "The uranium spot market was range-bound and under pressure for most of 2025, trading between $63/lb "
         "(April low) and $82–83/lb (September high) — a significant correction from the January 2024 peak of "
         "~$106/lb. Key drivers of the 2025 decline included: (1) speculative unwinding of long positions that "
         "built during the 2023–2024 run-up; (2) secondary supply from enrichment underfeeding and inventory "
         "drawdowns by utilities; and (3) macro uncertainty under the Trump administration affecting policy outlooks."
    )
    body(doc,
         "In contrast, the long-term contract price steadily rose from ~$80/lb to ~$86/lb across 2025, reflecting "
         "robust utility demand for multi-year fuel supply security. This divergence — weak spot, firm long-term — "
         "actually benefits Energy Fuels, as it is selling under long-term contracts (300k lbs in FY2025 at $71.06/lb) "
         "and building inventory for future delivery.",
         space_after=6
    )
    add_table(doc,
        headers=["Period", "U3O8 Spot ($/lb)", "LT Contract ($/lb)", "Commentary"],
        rows=[
            ["Jan 2024", "~$106", "~$68", "Post-Cameco/Kazatom supply fears peak"],
            ["Q2 2024", "~$85–90", "~$73", "Gradual pullback begins"],
            ["Q4 2024", "~$78–82", "~$78", "Convergence of spot & LT"],
            ["Q1 2025 (Apr low)", "~$63–65", "~$80", "18-month low; LT > Spot"],
            ["Q3 2025 (Sep high)", "~$82–83", "~$84", "Partial recovery"],
            ["Q4 2025", "~$70–76", "~$85", "Softening into year-end"],
            ["Jan 2026", "~$98–100", "~$87", "Sharp recovery; near 2-year highs"],
        ],
        col_widths=[1.8, 1.5, 1.7, 2.7]
    )
    body(doc, "Sources: UxC, TradeTech, Sprott Uranium Outlook 2026, ANS Nuclear Newswire.", italic=True, color=C_GREY, size=8.5)
    body(doc, "", space_after=6)

    add_image(doc, "uuuu_chart11_uranium_market.png", caption="Chart 11: Uranium Spot vs Long-Term Contract Price Trend (2024–Jan 2026)")

    heading(doc, "Structural Uranium Market Outlook", level=3)
    bullet(doc, "Global uranium mine supply deficit of ~130M lbs/year; demand accelerating from new reactor builds and data centers")
    bullet(doc, "6 new nuclear reactors connected to the grid in 2024 (China-led); >60 reactors under construction globally")
    bullet(doc, "US Prohibiting Russian-enriched uranium imports (2024 Prohibitions Act) structurally benefits domestic U.S. producers")
    bullet(doc, "Uranium futures rose to ~$100/lb in January 2026 — highest since February 2024")
    bullet(doc, "Energy Fuels is one of only 3 active U.S. uranium producers alongside Cameco-Cigar and enCore Energy")
    body(doc, "", space_after=6)

    heading(doc, "REE Market Context", level=3)
    body(doc,
         "Western rare earth supply chains remain critically concentrated in China, which controls ~85% of global "
         "REE processing. U.S. and allied government demand for domestic REE separation has accelerated, driven by "
         "defense/EV permanent magnet needs. Energy Fuels' White Mesa Mill is the only facility in the Western "
         "Hemisphere capable of producing separated heavy REEs (dysprosium, terbium) commercially outside China."
    )
    bullet(doc, "NdPr oxide price: ~$50–60/kg (2025); Dy oxide: ~$300–360/kg; Tb oxide: ~$1,400–1,600/kg")
    bullet(doc, "DOE and DOD are actively funding domestic REE supply chain development")
    bullet(doc, "Energy Fuels' NdPr qualified by Samsung SDI-type permanent magnet manufacturer (South Korea)")
    body(doc, "", space_after=8)

    # ── SECTION 4: 2026 GUIDANCE ────────────────────────────────────────────────
    page_break(doc)
    heading(doc, "4. Fiscal Year 2026 Guidance", level=2)

    heading(doc, "Uranium Production & Sales", level=3)
    add_table(doc,
        headers=["Metric", "2026 Guidance", "FY2025 Actual", "Change"],
        rows=[
            ["Mined U3O8 (Mlbs)", "2.0–2.5", "1.72", "+16% to +45%"],
            ["Processed/Finished (Mlbs)", "1.5–2.5", "1.015", "+48% to +146%"],
            ["Uranium Sales (Mlbs)", "1.5–2.0", "0.65", "+131% to +208%"],
            ["Avg Cost of Finished Inv. ($/lb)", "Low $30s (target)", "~$43", "–25%+ improvement"],
            ["Uranium COGS ($/lb, Pinyon Plain)", "$23–30", "~$43 (blended)", "Significant reduction"],
            ["  Mining / Transport", "$10–14/lb", "—", "—"],
            ["  Milling", "$13–16/lb", "—", "—"],
            ["Long-term Contracts", "6 through 2032", "6", "Stable"],
        ],
        col_widths=[2.7, 1.8, 1.5, 1.5]
    )
    body(doc, "", space_after=4)
    body(doc,
         "Management guided to a near-doubling of uranium sales volume in 2026, supported by: (1) continued Pinyon "
         "Plain high-grade ore processing at White Mesa; (2) potential restart of La Sal and Pandora mines; and (3) "
         "the 2.18M lb finished + in-process inventory entering 2026. The expected unit cost decline to the 'low $30s' "
         "implies gross margins could expand to 55%+ at current uranium prices (~$80–100/lb).",
         space_after=6
    )

    heading(doc, "REE 2026 Targets", level=3)
    bullet(doc, "Phase 1 (NdPr from monazite): ~850–1,000 tonnes NdPr/yr at full Phase 1B/1C capacity by 2027")
    bullet(doc, "Heavy REE commercial separation: Dy, Tb, and potentially Sm capacity commissioned Q4 2026 at White Mesa")
    bullet(doc, "Terbium oxide: First kilogram production targeted Q1 2026")
    bullet(doc, "Feasibility study (Phase 2): $410M capex; 5,513 t NdPr + 165 t Dy + 48 t Tb/yr; NPV $1.9B; IRR 33%")
    bullet(doc, "Phase 2 permitting: Begin 2026/2027; commissioning target late 2028 – early 2029")
    body(doc, "", space_after=4)

    heading(doc, "Capital Expenditure & Strategic", level=3)
    bullet(doc, "Capex 2026: Not explicitly guided; focus on White Mesa REE circuit upgrades and mine development")
    bullet(doc, "Donald Project (Australia, 49% JV with Astron): FID expected Q1 2026; AUD $520M total capex; AUD $80M EFA debt letter of support")
    bullet(doc, "Donald target production: H2 2027; heavy REE feedstock for White Mesa")
    bullet(doc, "Vara Mada Project (Madagascar): NPV $1.8B at 10% discount, ~38-yr mine life; investment agreement discussions ongoing with Government")
    bullet(doc, "Medical Isotope: Radium-226 R&D pilot facility commissioning 2026; commercial production target 2028")
    bullet(doc, "Management succession: Ross Bhappu (President → CEO) effective April 15, 2026; Mark Chalmers retires, remains 2-yr consultant")
    body(doc, "", space_after=6)

    add_image(doc, "uuuu_chart9_ree_roadmap.png", caption="Chart 9: REE Expansion NPV & EBITDA Roadmap by Phase")

    # ── SECTION 5: EARNINGS CALL HIGHLIGHTS ────────────────────────────────────
    page_break(doc)
    heading(doc, "5. Earnings Call Highlights (February 27, 2026)", level=2)

    heading(doc, "White Mesa Mill — Operations", level=3)
    body(doc,
         "The White Mesa Mill in Blanding, Utah remains the centerpiece of Energy Fuels' operations — the only "
         "conventional uranium mill currently operating in the United States and the only facility in the Western "
         "Hemisphere producing separated heavy rare earth oxides."
    )
    bullet(doc, "Mill licensed capacity: 8 million lbs U3O8/year")
    bullet(doc, "Conventional ore processing campaign commenced Q4 2025; running through Q2 2026")
    bullet(doc, "Peak throughput: ~350,000 lbs finished U3O8 produced in December 2025 alone")
    bullet(doc, "Average throughput demonstrated at ~250,000 lbs/month")
    bullet(doc, "REE pilot circuit producing Dy oxide at 99.9% purity; Tb oxide imminent")
    bullet(doc, "Cost improvements: COGS/lb declined from $53 (2024) → $43 (2025) → targeting low $30s (2026)")
    body(doc, "", space_after=4)

    heading(doc, "Pinyon Plain Mine — Arizona", level=3)
    body(doc,
         "Pinyon Plain is the primary driver of uranium production growth and one of the highest-grade uranium "
         "mines in U.S. history by management's account."
    )
    bullet(doc, "FY2025 mined ore: ~1,530,000 lbs U3O8 contained at ~1.62% eU3O8 average grade")
    bullet(doc, "Mine life and resource remain large; additional development drilling ongoing")
    bullet(doc, "Updated pre-feasibility study (PFS) in progress — may improve project economics and expand resource estimate")
    bullet(doc, "Processing costs (2026E): $23–30/lb total ($10–14 mining/transport + $13–16 milling)")
    body(doc, "", space_after=4)

    heading(doc, "La Sal Complex & Other Mines — Utah/Colorado", level=3)
    bullet(doc, "La Sal Complex (Utah) contributed ~190,000 lbs contained U3O8 to FY2025 mined total")
    bullet(doc, "Pandora Mine (Colorado): active but at reduced rates")
    bullet(doc, "Whirlwind Mine (Colorado): standby / care-and-maintenance")
    bullet(doc, "Management guided to potentially restart additional mines in 2026 as needed to meet 2.0–2.5M lb target")
    body(doc, "", space_after=4)

    heading(doc, "Alta Mesa ISR — Texas (Note: enCore Energy Asset)", level=3)
    body(doc,
         "Note: Alta Mesa ISR is operated by enCore Energy (EU), not Energy Fuels. Energy Fuels does not have "
         "direct operations at Alta Mesa. Energy Fuels' ISR exposure is through potential future ISR projects. "
         "This distinction is important when analyzing the company.",
         color=C_GREY, italic=True
    )
    body(doc, "", space_after=4)

    heading(doc, "REE Separation Facility — Strategic Vision", level=3)
    body(doc,
         "Management outlined the most detailed REE expansion roadmap to date on the earnings call:"
    )
    bullet(doc, "Phase 1 (current): NdPr separation from monazite; ~850–1,000 t NdPr/yr at full Phase 1B/1C scale")
    bullet(doc, "Phase 1 commercial-scale Dy/Tb/Sm separation: Target Q4 2026 commissioning at White Mesa")
    bullet(doc, "Phase 2 Feasibility Study (announced Jan 2026): $410M capex, 40-yr project, 5,513 t NdPr + 165 t Dy + 48 t Tb/yr")
    bullet(doc, "Phase 2 NPV: $1.9B standalone; $3.7B combined with Vara Mada (Madagascar) feedstock")
    bullet(doc, "Phase 2 + Vara Mada EBITDA: ~$765M/yr (first 15 years)")
    bullet(doc, "Phase 2 IRR: 33% post-tax; per-share NPV: $7.96/share (Phase 2 alone) to $15.26/share (Phase 2 + Vara Mada)")
    bullet(doc, "Donald Project (Australia) provides heavy REE feedstock — FID Q1 2026, production H2 2027")
    body(doc, "", space_after=4)

    heading(doc, "Key Strategic Announcements & Acquisitions", level=3)
    bullet(doc, "Australian Strategic Materials (ASM) acquisition: Energy Fuels agreed to acquire ASM (ASX:ASM) to add downstream rare earth metal alloy production — completing a fully integrated Western critical minerals supply chain")
    bullet(doc, "Two new long-term uranium supply contracts signed Q4 2025 (now 6 total through 2032)")
    bullet(doc, "Export Finance Australia issued non-binding AUD $80M debt letter of support for Donald Project")
    bullet(doc, "Vulcan Elements partnership: Joint venture to advance U.S. rare earth magnet security")
    bullet(doc, "Management succession: CEO Mark Chalmers retiring April 15, 2026; replaced by President Ross Bhappu")
    body(doc, "", space_after=8)

    # ── SECTION 6: ANALYST REACTIONS ───────────────────────────────────────────
    page_break(doc)
    heading(doc, "6. Analyst Reactions & Price Targets (Post-Earnings)", level=2)

    add_table(doc,
        headers=["Analyst / Firm", "Rating", "Price Target", "Change", "Key Commentary"],
        rows=[
            ["H.C. Wainwright", "Buy", "$27.25", "Raised (from $26.75)", "Strong uranium production ramp; Pinyon Plain PFS catalyst; REE pilot milestones de-risk Phase 1"],
            ["Consensus (6–8 analysts)", "Strong Buy", "$23.08 avg\n($15.50–$34.00 range)", "—", "7 Buy / 1 Hold / 0 Sell as of Mar 9, 2026"],
            ["Implied upside (avg target)", "—", "~24% vs current", "—", "Based on $23.08 avg target vs $18.67 current price"],
            ["Implied upside (HC W. target)", "—", "~46% vs current", "—", "Based on $27.25 vs $18.67 current price"],
        ],
        col_widths=[1.8, 0.8, 1.5, 1.3, 3.0]
    )
    body(doc, "", space_after=4)

    body(doc,
         "While Q4 2025 EPS missed consensus by $0.01, the headline revenue beat and the strong 2026 guidance "
         "(uranium sales 1.5–2.0M lbs vs 0.65M in 2025) drove generally constructive analyst commentary. "
         "The Phase 2 REE feasibility study NPV of $1.9B–$3.7B was viewed as a significant underappreciated "
         "asset at current market cap levels (~$4.5B). The ASM acquisition, adding downstream alloy capability, "
         "was seen as strategically completing the Western REE supply chain and potentially attracting government "
         "(DOE/DOD) offtake and financing support.",
         space_after=6
    )

    add_image(doc, "uuuu_chart10_price_targets.png", caption="Chart 10: Analyst Price Targets vs Current Price (March 2026)")

    # ── SECTION 7: STOCK PRICE & MARKET CAP ────────────────────────────────────
    heading(doc, "7. Stock Price & Market Context", level=2)

    add_table(doc,
        headers=["Metric", "Value"],
        rows=[
            ["Current Price (Mar 16, 2026)", "~$18.67"],
            ["Market Capitalization", "~$4.51B"],
            ["52-Week Range", "$3.20 – $27.90"],
            ["Year-to-Date Performance", "Significant decline from 52-wk high"],
            ["Exchange", "NYSE American (UUUU) / TSX (EFR)"],
            ["Shares Outstanding (approx.)", "~242M"],
            ["Enterprise Value (approx.)", "~$4.35B (net cash ~$162M adj. for conv. notes)"],
            ["EV / FY2025 Revenue", "~66x (early-stage/growth premium)"],
            ["EV / FY2026E Revenue (consensus)", "~17–20x (at 1.75M lbs @ $80/lb = $140M rev est.)"],
            ["Next Earnings Date", "~May 7, 2026 (Q1 2026)"],
        ],
        col_widths=[3.0, 4.5]
    )
    body(doc, "", space_after=4)
    body(doc,
         "UUUU's stock surged nearly 400% from its April 2025 lows (~$3.20) to its 52-week high of $27.90, "
         "driven by the $700M convertible note offering, REE milestones, and uranium production ramp. Since "
         "the January 2026 highs, the stock has retraced to ~$18.67 as uranium spot prices softened and "
         "broader market volatility increased. The market cap of ~$4.51B now trades at a substantial premium "
         "to current earnings but embeds significant optionality from the $3.7B Phase 2 + Vara Mada REE NPV.",
         space_after=8
    )

    # ── SECTION 8: HISTORICAL QUARTERLY DATA ───────────────────────────────────
    page_break(doc)
    heading(doc, "8. Historical Quarterly Data — Trend Analysis", level=2)

    add_table(doc,
        headers=["Quarter", "Revenue ($M)", "Net Inc/(Loss) ($M)", "EPS ($)", "U Sold (klbs)", "U Price ($/lb)", "U Revenue ($M)"],
        rows=[
            ["Q1 2024", "$25.3", "+$3.6", "+$0.02", "300", "$84.4", "$25.3"],
            ["Q2 2024", "~$16.2", "~($9.8)", "($0.06)", "~0", "—", "~$0"],
            ["Q3 2024", "~$23.7", "~($12.8)", "($0.07)", "~0", "—", "~$0"],
            ["Q4 2024", "~$39.9", "($28.8)", "($0.19)", "~150", "~$84", "~$12.6"],
            ["FY 2024", "$78.1", "($47.8)", "($0.28)", "450", "$87.2", "$37.9"],
            ["Q1 2025", "$16.9", "($26.3)", "($0.13)", "~50", "~$80", "~$7.0"],
            ["Q2 2025", "~$12.7", "($22.2)", "($0.10)", "~150", "~$79", "~$4.2"],
            ["Q3 2025", "$17.7", "($16.7)", "($0.07)", "240", "~$70", "$10.4"],
            ["Q4 2025", "$27.1", "~($20.9)", "($0.08)", "360", "$74.93", "~$27.0"],
            ["FY 2025", "$65.9", "($86.1)", "($0.38)", "650", "$74.21", "$48.2"],
        ],
        col_widths=[1.0, 1.1, 1.3, 0.8, 1.1, 1.1, 1.1]
    )
    body(doc, "Sources: Energy Fuels quarterly press releases (Q1–Q4 2024, Q1–Q4 2025); Zacks; StockTitan SEC filings.", italic=True, color=C_GREY, size=8.5)
    body(doc, "", space_after=4)

    body(doc,
         "Key trends observable in the quarterly data: (1) Q2 and Q3 2024 had $0 uranium sales as the company "
         "built inventory; (2) uranium sales accelerated sharply in H2 2025, with Q4 2025 representing the largest "
         "quarterly uranium revenue in company history; (3) unit economics improved consistently through 2025 "
         "(COGS/lb declining each quarter); (4) HMS revenue has trended toward zero as Kwale concluded; "
         "(5) the net loss trajectory in 2025 reflects heavy investment/ramp-up costs rather than structural "
         "operational weakness.",
         space_after=8
    )

    # ── SECTION 9: RISKS ───────────────────────────────────────────────────────
    heading(doc, "9. Key Risks", level=2)

    heading(doc, "Downside Risks", level=3, color=C_RED)
    bullet(doc, "Uranium price risk: Spot price remains volatile; a sustained fall below $60/lb would pressure margins")
    bullet(doc, "Execution risk: REE Phase 2 capex ($410M) requires financing — reliant on capital markets, government support, or offtake")
    bullet(doc, "Dilution risk: $700M convertible notes create potential dilution at $20.34/share conversion price; ~34.4M shares if fully converted")
    bullet(doc, "Regulatory / permitting risk: Vara Mada (Madagascar) faces government negotiations; Donald Project environmental approvals")
    bullet(doc, "REE pricing risk: NdPr, Dy, Tb prices subject to China supply policy and global EV demand fluctuation")
    bullet(doc, "Management transition: CEO succession (Bhappu replaces Chalmers) introduces execution continuity risk")
    body(doc, "", space_after=4)

    heading(doc, "Upside Catalysts", level=3, color=C_GREEN)
    bullet(doc, "Uranium price recovery toward $100+/lb would drive significant earnings leverage on 1.5–2.0M lb 2026 sales plan")
    bullet(doc, "DOE/DOD contract awards for REE supply — government offtake would de-risk Phase 2 construction financing")
    bullet(doc, "Phase 2 REE Final Investment Decision and financing announcement")
    bullet(doc, "Donald Project (Australia) FID confirmation and commencement of mining")
    bullet(doc, "Vanadium inventory monetization — 905k lbs V2O5 could generate $5–7M if sold at current prices")
    bullet(doc, "Pinyon Plain PFS update with improved resource estimate or mine-life extension")
    bullet(doc, "Medical isotope (Ra-226) commercial agreements — provides additional critical minerals diversification")
    body(doc, "", space_after=8)

    # ── FOOTER / SOURCES ───────────────────────────────────────────────────────
    divider(doc)
    heading(doc, "Sources & Disclosures", level=3, color=C_GREY)
    sources = [
        "Energy Fuels Inc. Press Release: '2025 Results and 2026 Guidance' (Feb 26, 2026) — investors.energyfuels.com",
        "Energy Fuels Inc. Press Release: 'Year-End Production and Sales Exceeding Guidance' (Dec 29, 2025)",
        "Energy Fuels Inc. Press Release: 'Q3-2025 Results' (Nov 3, 2025)",
        "Energy Fuels Inc. Press Release: 'Q2-2025 Results' (Aug 6, 2025)",
        "Energy Fuels Inc. Press Release: 'Q1-2025 Results' (May 7, 2025)",
        "PRNewswire: 'Energy Fuels Announces 2025 Results and 2026 Guidance' (Feb 26, 2026)",
        "H.C. Wainwright Research: Price target raise to $27.25 (Feb 27, 2026) — investing.com",
        "Yahoo Finance / Zacks: Q4 2025 earnings summary, consensus data",
        "GuruFocus / Investing.com: Q4 2025 earnings call highlights",
        "Sprott: 'Uranium Outlook 2026'; 'Uranium's Tale of Two Markets'",
        "Nasdaq.com: 'Uranium Price Forecast: Top Trends for Uranium in 2026'",
        "TipRanks: 'Energy Fuels Earnings Call Highlights Bold Growth Pivot'",
        "StockTitan: UUUU SEC Filing (10-Q) — Q3 2025 revenue $17.7M",
        "MarketBeat / WallStreetZen / StockAnalysis: Analyst consensus data",
        "ANS Nuclear Newswire: Uranium spot price data 2025",
    ]
    for s in sources:
        bullet(doc, s, color=C_GREY)
    body(doc, "", space_after=4)
    body(doc,
         "DISCLAIMER: This report is for informational purposes only. It does not constitute investment advice or "
         "a solicitation to buy or sell securities. All financial data is sourced from public filings and press "
         "releases. Estimates marked 'est.' are derived from partial data and may differ from official reported figures. "
         "Past performance does not guarantee future results.",
         italic=True, color=C_GREY, size=8.5
    )

    # ── SAVE ────────────────────────────────────────────────────────────────────
    out_path = os.path.join(BASE, "UUUU_Q4_FY2025_Earnings_Update.docx")
    doc.save(out_path)
    print(f"Saved: {out_path}")


if __name__ == "__main__":
    build_report()
